### ISSUE TITLE
Refrain from outputting a error code

### ISSUE THREAD

**Issue by nicorikken** [CISOfy/lynis-ansible#5]
Lynis returns an error code when warnings occur. Under normal circumstances this prevents a playbook from continuing, say across servers. Ideally there would be an easy way (other than ignore warnings flag) to prevent the error code.

**Comment by mboelen** [comment]
Is this still happening with the latest GitHub code as well?

**Comment by nicorikken** [comment]
I can verify. The current script checks out the Cisofy files, version 2.2.0. Can the master branch be considered 'stable' to be included as an option in the Ansible script? What would be a good title for such a repo checkout option? e.g. 'development', 'latest', 'testing' ?

**Comment by mboelen** [comment]
Yes, we consider the master branch to be development, yet stable enough for production use.

**Comment by ghost** [comment]
@mboelen Verified.

```
[lynis] git branch -l
* (detached from 2.2.0)
  master
[lynis] ./lynis audit system -q &> /dev/null
[lynis] echo $?
78
[lynis]
```

**Comment by mboelen** [comment]
Current release should not give that error code, depending on how you have your profile configured. Can you check if it is still the case?

**Comment by nicorikken** [comment]
Thanks :+1: Having become more aware of exit codes recently, I was already considering writing a exit-code wrapper in bash. If upstream solves this, that is fine for me as well.
Current checkout seems fine on my Debian Testing laptop (having tested the current master vs. a 2.2.0 checkout) If I get to it, I'll give it a try via Ansible to verify.

**Comment by mboelen** [comment]
Should be good now, and new version is official release. Closing therefore this item. Thanks for reporting.
