### ISSUE TITLE
[TOOL-5002] detect Ansible as system management tool

### ISSUE THREAD

**Issue by lpirl** [CISOfy/lynis-ansible#8]
One approach could be to read the syslog. Ansible produces lines like:

```
 Jun  4 17:03:00 MyHost ansible-git: …
 Jun  4 17:03:04 MyHost ansible-file: …
 Jun  4 17:03:06 MyHost ansible-apt: …
```

Not sure how platform dependent that is, thought…

**Comment by ghost** [comment]
@lpirl When your ansible produces these lines?

**Comment by ghost** [comment]
@mboelen I think this issue should be moved to [Lynis](https://github.com/CISOfy/lynis) project.

**Comment by lpirl** [comment]
@kboratynski ups, this should definitely be moved. Sorry, accident.

**Comment by lpirl** [comment]
moved to CISOfy/lynis#212
